### ISSUE TITLE
Feature Request: Support for np.bool_

### ISSUE THREAD

**Issue by alexanderswerdlow** [xl0/lovely-numpy#12]
Currently, printing an ndarray of dtype bool, causes the following:

```
TypeError: sequence item 1: expected str instance, numpy.dtypes.BoolDType found
```

This occurs with a very simple case:
```
lo(np.ones((3,), dtype=bool))
```

It would be great if this could be supported [or at least the error turned off for bool]!

**Comment by xl0** [comment]
@alexanderswerdlow Thank you for the report. I pushed a fix into git.
Could you please try it and confirm everything works correctly?

`pip install git+https://github.com/xl0/lovely-numpy.git`

**Comment by alexanderswerdlow** [comment]
@xl0 Thanks so much for the fix, it works great now!

**Comment by xl0** [comment]
@alexanderswerdlow Thank you. I pushed out a new release, please switch back to the package from pypi:

`pip install -U lovely-numpy` - should install  `0.2.11`
