### ISSUE TITLE
Feature request: `.gray` for previewing grayscale images

### ISSUE THREAD

**Issue by intrepidlemon** [xl0/lovely-numpy#13]
This should ideally work the same as `.rgb`, but instead of a 3D array (CHW), it should be a 2D array (HW). 

This is something that is frequently required (when you only want to visualize one channel, frequently in medical imaging, or any other spatial imaging modality that does not capture data in exactly three channels).

**Comment by xl0** [comment]
`.chans` ?

**Comment by xl0** [comment]
@intrepidlemon Does `.chans` do the trick for you?

**Comment by intrepidlemon** [comment]
ah I see. that works! thank you!
