### ISSUE TITLE
Display min/max as int when dtype is int

### ISSUE THREAD

**Issue by xl0** [xl0/lovely-numpy#6]
Currently: `tensor[256] x∈[2.000, 999.000] μ=496.613 σ=274.077 i64`
Should be: `tensor[256] x∈[2, 999] μ=496.613 σ=274.077 i64`

**Comment by JohannesStutz** [comment]
I'll try and implement this!

**Comment by JohannesStutz** [comment]
At least in my current environment (conda environment on Windows 10, with Python 3.9), this works fine already, without changing anything.
I can't try this out on a Linux system at the moment, but can look into it next week.

**Comment by xl0** [comment]
You are right, sorry about this.

It used to be an issue, but looks like it solved itself when I moved the implementation into `lovely-numpy`.
