### ISSUE TITLE
Monkey business v2

### ISSUE THREAD

**Issue by RuRo** [xl0/lovely-numpy#7]
I understand that the `lovely_numpy.monkey_patch()` only patches `__repr__` because of the C extension business, but I think that even with that restriction, we could still improve the current UX.

For example, once you apply the `monkey_patch()` there is currently no (user discoverable) way to revert it and the `lovely` function doesn't work as expected in `plain` and `verbose` modes. For example,

```python
lovely_numpy.monkey_patch()
x = np.arange(20)
print(lovely(x, verbose=True))
```

Expected output:
```
ndarray[20] i64 x∈[0, 19] μ=9.500 σ=5.766
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])
```

Actual output:
```
ndarray[20] i64 x∈[0, 19] μ=9.500 σ=5.766
ndarray[20] i64 x∈[0, 19] μ=9.500 σ=5.766
```

# Proposed solution

1) Provide a `lovely_numpy.monkey_unpatch()` function, that calls `np.set_string_function(None, ...)`
2) Keep track, if we are currently in a monkey-patched state or not
3) If we are currently already monkey-patched, then `lovely_numpy.utils.plain_repr`/`plain_str` should do something like
```python
def plain_repr(x):
    # If we are currently patched, temporarily unpatch,
    # otherwise plain_repr won't actually be plain
    if _currently_patched:
        try:
            monkey_unpatch()
            return plain_repr(x)
        finally:
            monkey_patch()

    # Otherwise, do the current plain_repr
    return x._plain_repr() if hasattr(type(x), "_plain_repr") else repr(x)
```
Btw, what is the point of `_plain_repr` lookup here? I don't see it being set anywhere.

# Bonus

Although we can't monkey-patch `x.p`/`x.v`/`x.deeper`/`x.rgb`/`x.plt`/`x.chans`, it might still make sense to provide these properties on the `StrProxy` class, so that the user can do

```python
from lovely_numpy import lovely as L
...

L(spicy).v
# instead of spicy.v

L(spicy).p
# instead of spicy.p

L(numbers).deeper
L(numbers).deeper(2)
# instead of numbers.deeper

... # etc etc
```

**Comment by xl0** [comment]
Hi! Thank you for putting so much thought into it! :two_hearts:

Yes, `lovely(x, verbose=True)` was supposed to be working, and the current behaviour is a bug.

In `lovely-tensors`, `monkey_patch()` saves the old repr into `_plain_repr`, and I expect to do the same in `lovely-jax`. This does not happen in `lovely-numpy`, and I guess I should stop trying to make `plain_repr` generic across backends. Let's make it numpy-specific.

Your solution looks good, except I would use `np.set_string_function(None, True)` for it. Let's keep the current `plain_repr` in `utils.utils.ipynb` as is, as it's currently used by `lovely-tensors`, and create a replacement that lives in `repr_str.ipynb`

Would you like to submit a PR? I'm using `nbdev` for this project, and I will come up with a how-to-contrbute document soon, so please let me know if it's confusing in any way. The key command is `nbdev_prepare`.

I love the Bonus idea! Would you like to work on it too?

**Comment by xl0** [comment]
@RuRo , Monkey-patching was just too much of a mess for Numpy.

I've reworked the UX inspired by your `L` idea, and I like the consistency much better. What do you think? 
Have not pushed to `pypi` yet.

**Comment by xl0** [comment]
Released as 0.2.0, please give it a try.

**Comment by RuRo** [comment]
@xl0 did you remove the `np.set_string_function` monkeypatching mechanism? Why?

The new `Lo` mechanism works fine, but I still think, that being able to set the "default" printing mechanism for arrays without wrapping it in `Lo` is useful.

**Comment by xl0** [comment]
It felt inconsistent and led to having 3 different ways to do the same thing, `Lo`, `lovely()`, and `monkey_patch()`.

But if you think it's useful, I'll add it back tomorrow with `plain_repr` fixed.

**Comment by RuRo** [comment]
> But if you think it's useful, I'll add it back tomorrow with plain_repr fixed.

Yes, that would be great, thank you. The new `Lo` interface is very nice, but you still need to manually wrap each displayed array, which is kind of a pain. I would prefer to have a "sane" representation by default (with `monkey_patch`) and then customize it with an explicit `Lo` call, whenever needed.

**Comment by xl0** [comment]
I think I found a nice solution.
Please see the README and https://xl0.github.io/lovely-numpy/03d_utils.config.html#repr-and-str

Would you have any thoughts on it?

**Comment by RuRo** [comment]
@xl0 LGTM! :smile:

**Comment by xl0** [comment]
I will add a `lo()` function in the next release because hitting Shift to type `Lo()` is a tiny bit annoying in practice.
