### ISSUE TITLE
.chans seems to work on a [-1, 1] interval

### ISSUE THREAD

**Issue by aenglebert** [xl0/lovely-numpy#8]
Hello,

Thank you for this really great library.

I noticed that .chans seems to apply the colormap from [-1,1] instead of [0,1] as described in the documentation.
https://github.com/xl0/lovely-numpy/blob/97c33a054936714653ab6783041feb01428b6863/README.md?plain=1#L167

Exemple to reproduce:

```
import numpy as np
from lovely_numpy import lo

sample = np.random.rand(14, 14, 1)
norm_01 = (sample - sample.min()) / (sample.max() - sample.min())
norm_11 = 2*norm_01 - 1

print(lo(norm_01))
display(lo(norm_01).chans(scale=15))
display(lo(norm_01).chans(cmap="jet", scale=15))

print(lo(norm_11))
display(lo(norm_11).chans(scale=15))
display(lo(norm_11).chans(cmap="jet", scale=15))


```
array[14, 14, 1] n=196 x∈[0., 1.000] μ=0.527 σ=0.213
![image](https://user-images.githubusercontent.com/16444971/205937771-b509037d-b11b-49ab-bb30-534b84540988.png)
![image](https://user-images.githubusercontent.com/16444971/205935022-f6ee2df0-7c90-4bba-bde9-8bc3ec11d33f.png)

array[14, 14, 1] n=196 x∈[-1.000, 1.000] μ=0.034 σ=0.590
![image](https://user-images.githubusercontent.com/16444971/205937795-8975cd25-79a5-48b9-97cb-db63e2c06b08.png)
![image](https://user-images.githubusercontent.com/16444971/205935037-67ed86dd-3f5d-467f-aab6-ebed127a52f8.png)

I found this line that seems to be designed to change a [-1, 1] to a [0, 1] as a possible cause for the trouble:
 https://github.com/xl0/lovely-numpy/blob/97c33a054936714653ab6783041feb01428b6863/lovely_numpy/utils/colormap.py#L62

I suppose that the [-1,1] range could also be a valid range that someone would want to visualise, so multiple solutions could exist, the main options I see are:
- Change the code to use the [0, 1] range
- Change the documentation to mention [-1,1] instead of [0,1]
- Add an argument to chans to allow to choose the range to use

What is you opinion about that?

Thank you!

**Comment by xl0** [comment]
Updated the README. Please let me know if you spot any other issues.

**Comment by aenglebert** [comment]
It happens ;-).

Thank you for the feedback!

I mainly use colormaps like Jet and Turbo, so I can't help you much with all varieties of colormaps, but I agree that [-1,1] seems to be a good default choice, especially for divergent cards.

I did try it with an option to specify a viewing range if you want to take a look:
https://github.com/aenglebert/lovely-numpy/commit/5560be2d4633780cb551ba30cb58690e4f4ff752

I don't know if it's a better approach to do this or to let the user normalize on their own, probably a matter of phylosophy.
For example, in my case, I have mostly heat maps between [0,1], but it's not hard to convert them to [-1,1] to view them.

ps: I'm not used to automatic code generation from the jupyter notebook you use, so I changed both in the .ipynb and .py but my commit is probably a bit wild.

**Comment by xl0** [comment]
Thank you. I changed the range because I'm working on a universal normalization function. The API will look like

`lo(x).n(...)`, which can be chained with all the other functions. It will have a few normalization schemes and shortcuts, including linear 0..1 - > -1..1 conversion.

**Comment by aenglebert** [comment]
Very good idea! 
It's indeed more versatile.
I'll look forward to it.
